name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/mobile-ui-kit/images/radio.png
    - assets/mobile-ui-kit/images/bg.png
    - assets/mobile-ui-kit/images/icon-send.png
    - assets/mobile-ui-kit/images/emoji.png
    - assets/mobile-ui-kit/images/rectangle.png
    - assets/mobile-ui-kit/images/ios-status-bar-white.png
    - assets/mobile-ui-kit/images/ios-status-bar-white-mz1.png
    - assets/mobile-ui-kit/images/key-light.png
    - assets/mobile-ui-kit/images/ellipse-6-bg.png
    - assets/mobile-ui-kit/images/tint-layer.png
    - assets/mobile-ui-kit/images/rectangle-9q3.png
    - assets/mobile-ui-kit/images/bg-gt1.png
    - assets/components/images/dictation.png
    - assets/mobile-ui-kit/images/rectangle-e1P.png
    - assets/mobile-ui-kit/images/ios-status-bar-black.png
    - assets/components/images/rectangle-FBf.png
    - assets/mobile-ui-kit/images/ios-status-bar-white-GWu.png
    - assets/mobile-ui-kit/images/profile-photo-bg.png
    - assets/mobile-ui-kit/images/icon-x.png
    - assets/mobile-ui-kit/images/bg-gSd.png
    - assets/mobile-ui-kit/images/rectangle-Q3s.png
    - assets/mobile-ui-kit/images/checkbox-empty.png
    - assets/mobile-ui-kit/images/bg-TEq.png
    - assets/mobile-ui-kit/images/dictation-Jr5.png
    - assets/components/images/bg-4PK.png
    - assets/mobile-ui-kit/images/pagination.png
    - assets/mobile-ui-kit/images/vector.png
    - assets/mobile-ui-kit/images/bg-hKo.png
    - assets/components/images/bg-Az5.png
    - assets/components/images/bg-wE9.png
    - assets/mobile-ui-kit/images/ios-status-bar-black-ksj.png
    - assets/mobile-ui-kit/images/ios-status-bar-black-GZX.png
    - assets/mobile-ui-kit/images/ios-status-bar-black-1GD.png
    - assets/components/images/bg-ZoX.png
    - assets/mobile-ui-kit/images/outer-circle.png
    - assets/mobile-ui-kit/images/emoji-AHX.png
    - assets/mobile-ui-kit/images/rectangle-Jed.png
    - assets/mobile-ui-kit/images/bg-sSq.png
    - assets/mobile-ui-kit/images/ios-status-bar-black-VkD.png
    - assets/mobile-ui-kit/images/key-light-S9f.png
    - assets/mobile-ui-kit/images/rectangle-QVo.png
    - assets/components/images/checkbox-empty-9yB.png
    - assets/mobile-ui-kit/images/rectangle-TZB.png
    - assets/mobile-ui-kit/images/key-light-uvy.png
    - assets/mobile-ui-kit/images/key-light-gB3.png
    - assets/components/images/ios-status-bar-white-yuT.png
    - assets/components/images/checkbox-filled.png
    - assets/mobile-ui-kit/images/rectangle-xEu.png
    - assets/mobile-ui-kit/images/pagination-jS1.png
    - assets/mobile-ui-kit/images/ios-status-bar-black-br9.png
    - assets/components/images/bg-753.png
    - assets/mobile-ui-kit/images/rectangle-Ldw.png
    - assets/mobile-ui-kit/images/image2023-10-23220735123-modified-1.png
    - assets/components/images/checkbox-empty-3W1.png
    - assets/mobile-ui-kit/images/bg-aqF.png
    - assets/mobile-ui-kit/images/ios-status-bar-black-cmw.png
    - assets/components/images/categories.png
    - assets/mobile-ui-kit/images/ios-status-bar-black-GkZ.png
    - assets/mobile-ui-kit/images/ios-status-bar-white-zAm.png
    - assets/mobile-ui-kit/images/bg-YCH.png
    - assets/mobile-ui-kit/images/bg-ZDB.png
    - assets/mobile-ui-kit/images/key-light-F61.png
    - assets/mobile-ui-kit/images/bg-QDo.png
    - assets/components/images/icon-checkmark.png
    - assets/mobile-ui-kit/images/bg-XZK.png
    - assets/mobile-ui-kit/images/bg-BsP.png
    - assets/mobile-ui-kit/images/dictation-BAZ.png
    - assets/mobile-ui-kit/images/rectangle-8Lh.png
    - assets/mobile-ui-kit/images/ios-status-bar-black-sp5.png
    - assets/mobile-ui-kit/images/pagination-doF.png
    - assets/components/images/ios-status-bar-black-YvD.png
    - assets/mobile-ui-kit/images/icon-send-6wj.png
    - assets/mobile-ui-kit/images/rectangle-2Kb.png
    - assets/mobile-ui-kit/images/bg-Gzd.png
    - assets/mobile-ui-kit/images/dictation-B61.png
    - assets/mobile-ui-kit/images/emoji-8G9.png
    - assets/mobile-ui-kit/images/ios-status-bar-black-5SH.png
    - assets/mobile-ui-kit/images/ellipse-6-bg-E5w.png
    - assets/components/images/bitmap.png
    - assets/mobile-ui-kit/images/key-light-gnu.png
    - assets/mobile-ui-kit/images/vector-ACH.png
    - assets/components/images/emoji-HXo.png
    - assets/components/images/radio-3G5.png
    - assets/mobile-ui-kit/images/bg-kLq.png
    - assets/components/images/bitmap-57w.png
    - assets/mobile-ui-kit/images/radio-eaM.png
    - assets/components/images/delete.png
    - assets/components/images/key-light-aD7.png
    - assets/mobile-ui-kit/images/key-light-KwP.png
    - assets/components/images/dictation-zk1.png
    - assets/components/images/bg-KnH.png
    - assets/mobile-ui-kit/images/dictation-j6q.png
    - assets/mobile-ui-kit/images/pagination-VFf.png
    - assets/mobile-ui-kit/images/rectangle-yfw.png
    - assets/components/images/key-light-uZb.png
    - assets/mobile-ui-kit/images/key-light-GQ9.png
    - assets/mobile-ui-kit/images/emoji-cyo.png
    - assets/components/images/globe.png
    - assets/components/images/bitmap-Uwj.png
    - assets/mobile-ui-kit/images/image2023-10-23220735123-modified-1-oSZ.png
    - assets/components/images/bitmap-TPw.png
    - assets/components/images/bitmap-Biq.png
    - assets/components/images/bitmap-sbX.png
    - assets/mobile-ui-kit/images/radio-MS1.png
    - assets/components/images/ios-keyboard-light-dictation.png
    - assets/mobile-ui-kit/images/bg-HF7.png
    - assets/components/images/bg-49P.png
    - assets/components/images/rectangle-9yT.png
    - assets/mobile-ui-kit/images/ios-status-bar-black-UF3.png
    - assets/components/images/rectangle-1km.png
    - assets/components/images/checkbox-filled-tJm.png
    - assets/mobile-ui-kit/images/image2023-10-23220355002-modified-1.png
    - assets/components/images/bitmap-8t1.png
    - assets/components/images/bitmap-iC9.png
    - assets/components/images/bitmap-Nmo.png
    - assets/components/images/bitmap-g5X.png
    - assets/components/images/bitmap-ZAR.png
    - assets/components/images/bitmap-GQh.png
    - assets/mobile-ui-kit/images/pagination-Fy3.png
    - assets/components/images/bitmap-aWm.png
    - assets/components/images/bitmap-yiZ.png
    - assets/components/images/pagination-iTB.png
    - assets/components/images/bitmap-Zhs.png
    - assets/components/images/bitmap-JCy.png
    - assets/components/images/bitmap-P4D.png
    - assets/components/images/bitmap-RgM.png
    - assets/components/images/bitmap-nY9.png
    - assets/components/images/bitmap-rkZ.png
    - assets/components/images/vector-4Qh.png
    - assets/components/images/bitmap-46V.png
    - assets/components/images/grinning-face.png
    - assets/components/images/bitmap-Bso.png
    - assets/components/images/bg-LNV.png
    - assets/components/images/bitmap-kNu.png
    - assets/components/images/bitmap-MRj.png
    - assets/components/images/bitmap-uub.png
    - assets/components/images/bitmap-qcV.png
    - assets/components/images/bitmap-Skh.png
    - assets/components/images/bitmap-wgm.png
    - assets/components/images/bitmap-63s.png
    - assets/components/images/bitmap-1bP.png
    - assets/components/images/bitmap-JGy.png
    - assets/components/images/bitmap-oYV.png
    - assets/components/images/bitmap-xRP.png
    - assets/components/images/bitmap-YeV.png
    - assets/components/images/bitmap-1rq.png
    - assets/components/images/bitmap-Z4u.png
    - assets/components/images/bitmap-gzu.png
    - assets/components/images/bitmap-NuF.png
    - assets/components/images/auto-group-d4mf.png
    - assets/components/images/bitmap-6LH.png
    - assets/components/images/auto-group-2uo3.png
    - assets/components/images/auto-group-rynr.png
    - assets/components/images/auto-group-qbum.png
    - assets/components/images/background.png
    - assets/components/images/auto-group-5vrk.png
    - assets/components/images/auto-group-en7j.png
    - assets/components/images/auto-group-8oyv.png
    - assets/components/images/auto-group-5h8d.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
